name: wk
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  args: ^2.0.0
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.5
  http: ^0.13.5
  mqtt_client: ^9.7.1
  rfc_6901: ^0.1.1
  rxdart: ^0.27.5
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  supabase: ^0.3.6
  typed_data: ^1.3.1
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
